job_link:
  - uzoe
  - trabajo
  - thecareerwallet
  - bebee
  - uk.talent.com
  - www.recruit.net
  - itjobboard
  - newstaffuk
  - vacancystation
  - fidanto
  - careermap
  - jobsitejobs
  - debut.careers
  - fish4
  - jobs24
  - goodjobsnearme
  - jozoo
  - joblift
  - jobrapido
  - tarta
company:
  - The Training Room
  - NUYEW LTD
  - IT Career Switch
description:
  - The Training Room
  - Guaranteed job after training
  - successful completion of the training course
