url:
  - uzoe
  - trabajo
  - thecareerwallet
  - bebee
  - uk.talent.com
  - www.recruit.net
  - itjobboard
  - newstaffuk
  - vacancystation
  - fidanto
  - careermap
  - jobsitejobs
  - debut.careers
  - fish4
  - jobs24
  - goodjobsnearme
  - jozoo
  - joblift
  - jobrapido
  - tarta
  - jora
  - topdownsouthjobs
  - jooble
  - the-dots
company:
  - The Training Room
  - NUYEW LTD
  - IT Career Switch
  - RemoteWorker UK
description:
  - The Training Room
  - Guaranteed job after training
  - successful completion of the training course
  - one off cost of
