title:
  - graduate
  - grad
description:
  - 2.1 Degree in Computer Science
  - Batchelors degree or higher in Computer Science
  - Master's or Bachelor degree in IT
  - Computer Science or similar STEM
  - 2.1 or above in a STEM discipline
  - Commercial software engineering experience