title:
  - somethingsoitdoesnterror
description:
  - 2.1 Degree in Computer Science
  - Batchelors degree or higher in Computer Science
  - Master's or Bachelor degree in IT
  - Computer Science or similar STEM
