title:
  - mid-level
  - senior
  - mid
  - manager
description:
  - 1-2 years
  - 1+ year
  - commercial C++ development
  - good knowledge of communication protocols
  - 2+ years
  - Commercial software engineering experience