level:
  - junior
  - grad
  - graduate
  - entry
  - apprentice
  - apprenticeship
  - trainee
  - jr.
role:
  - developer
  - engineer
  - software development
  - software engineering
  - web development
  - programmer
  - programming
software_indicator:
  - product
  - software
  - web
  - website
  - webapp
  - web-app
# Stack
  - frontend
  - front-end
  - front end
  - backend
  - back-end
  - back end
  - fullstack
  - full-stack
  - full stack
  - server-side
  - server side
  - application
  - mobile
  - android
  - ios
  - native
  - systems
  - infrastructure
  - machine learning
  - machine-learning
  - microservices
  - micro services
  - api
  - database
  - data
# languages
  - go
  - javascript
  - java
  - c++
  - c#
  - python
  - ruby
  - .net
  - php
  - scala
  - groovy
  - html
  - css
  - elixir
  - swift
  - perl
  - kotlin
  - rust
  - dart
  - unity
  - node
  - dotnet
# Frameworks
  - django
  - flask
  - symfony
  - jquery
  - express
  - asp
  - sinatra
  - drupal
  - spring
  - react
  - angular
  - laravel
  - wordpress
  - rails
  - salesforce