level:
  - junior
  - grad
  - graduate
  - entry
  - apprentice
  - apprenticeship
  - trainee
  - jr.
  - Junr
role:
  - developer
  - engineer
  - software development
  - software engineering
  - web development
  - programmer
  - programming
software_terms:
  - product
  - software
  - web
  - website
  - webapp
  - web-app
# Stack
  - frontend
  - front-end
  - front end
  - backend
  - back-end
  - back end
  - fullstack
  - full-stack
  - full stack
  - server-side
  - server side
  - application
  - mobile
  - android
  - ios
  - native
  - systems
  - infrastructure
  - machine learning
  - machine-learning
  - microservices
  - micro services
  - api
  - database
  - data
  - software development
  - software engineering
  - web development
languages:
  - go
  - javascript
  - java
  - c++
  - c#
  - python
  - ruby
  - .net
  - php
  - scala
  - groovy
  - html
  - css
  - elixir
  - swift
  - perl
  - kotlin
  - rust
  - dart
  - unity
  - node
  - dotnet
  - sql
  - github
  - git
frameworks:
  - django
  - flask
  - symfony
  - jquery
  - express
  - asp
  - sinatra
  - drupal
  - spring
  - react
  - angular
  - AngularJS
  - reactjs
  - laravel
  - wordpress
  - rails
  - salesforce
  - WordPress
description_only_software_terms:
  - computer science
  - code
  - coding
  - programming
  - devops
  - dev ops
  - Graduate Developer
  - re-factor existing code
  - MySQL
  - Linux
  - Microsoft web server
  - CICD
  - CI/CD
  - aws
  - Azure
<<<<<<< Updated upstream
  - REST
  - Software Engineering
  - software development
=======
  - TDD
  - BDD
  - SCRUM
  - agile
>>>>>>> Stashed changes
