title:
  - bootcamp
  - self-taught
  - career changer
  - Coding Academy
  - career-changer
  - self taught
description:
  - self-taught
  - bootcamp
  - career-changers
  - career-changer
  - career changer
  - coding academy
  - self taught
  - Boot Camp