role:
  - developer
  - engineer
  - software development
  - software engineering
  - web
  - programmer
  - programming
  - coding
  - technology
  - technical lead
  - tech lead
software_terms:
  - product
  - software
  - web
  - website
  - webapp
  - web-app
  # Stack
  - frontend
  - front-end
  - front end
  - backend
  - back-end
  - back end
  - fullstack
  - full-stack
  - full stack
  - server-side
  - server side
  - application
  - mobile
  - android
  - ios
  - native
  - systems
  - infrastructure
  - machine learning
  - machine-learning
  - microservices
  - micro services
  - api
  - database
  - data
  - software development
  - software engineering
  - web development
  - lead
  - staff
  - manager
  - sr
description_only_software_terms:
  - computer science
  - code
  - coding
  - programming
  - devops
  - dev ops
  - Graduate Developer
  - re-factor existing code
  - MySQL
  - Linux
  - Microsoft web server
  - CICD
  - CI/CD
  - aws
  - Azure
  - REST
  - Software Engineering
  - software development
  - TDD
  - BDD
  - SCRUM
  - agile
  - BitBucket
  - git
  - github
