title:
  - mid-level
  - senior
  - mid
  - manager
description:
  - 1-2 years
  - 1+ year
  - commercial C++ development
  - good knowledge of communication protocols
  - 2+ years
  - Commercial software engineering experience
  - at least 2 years
  - at least 3 years
  - minimum of 2 years
  - minimum of 3 years
  - some commercial experience
