title:
  - mid-level
  - senior
  - mid
  - manager
description:
  - 1-2 years
  - 1+ year
  - commercial C++ development
  - good knowledge of communication protocols
  - 2+ years
  - Commercial software engineering experience
  - at least 2 years
  - at least 3 years
  - minimum of 2 years
  - minimum of 3 years
  - some commercial experience
  - C++ development on high performance
  - at least 1 year
  - at least 2 year
  - at least 3 year
  - 1.5 to 2 years
  - 2 years plus
  - 1 year plus