title:
  - mid-level
  - senior
  - mid
  - manager
description:
  - two year
  - two years
  - two years,
  - two years'
  - one year
  - one year,
  - one years
  - one years'
  - 1-2 years
  - 1-2 years’
  - 1+ year
  - 1 years+
  - commercial C++ development
  - good knowledge of communication protocols
  - 2+ years
  - Commercial software
  - at least 2 years
  - at least 3 years
  - minimum of 2 years
  - minimum of 3 years
  - C++ development on high performance
  - at least 1 year
  - at least 2 year
  - at least 3 year
  - 1.5 to 2 years
  - 2 years plus
  - 1 year plus
  - development on high performance production systems
  - You have commercial
  - years commercial
  - year commercial
  - commercial experience
  - 2-3 years experience
  - 2-3 year's experience
  - 2-3 years' experience
  - a years' experience
  - a years experience
  - 2-6 years
  - 2-4 years
  - 2-5 years
  - 1+ year(s)
  - in a commercial environment
  - 1-year
  - 2-years
  - 1-2yrs
  - 1-2 yrs
  - few years
  - 2 years
  - 1yrs
  - 2yrs
  - 1 yrs
  - 2 yrs
  - 1 year
  - 1-3 years
  - twelve months
  - 1/2+ years
  - 1/2 years'
  - 1/2 years
  - 1/2 yrs
  - 1 years'
  - 2 years'
  - 3 years'
  - 4 years'
  - Commercial Java development experience
  - Commercial experience
  - commercial web
  - Commercial object orientated
  - working commercially
  - experience working on complex products
  - professional experience
  - professional javascript experience
  - professional software development experience
  - professional development experience
