title:
  - grad
  - graduate
description:
  - 2.1 Degree in Computer Science
  - Batchelors degree or higher in Computer Science
  - Master's or Bachelor degree in IT
  - Computer Science or similar STEM
  - IT graduate
  - Degree in computer
  - degree in Computer Science
  - Computer Science Graduate
  - 1st class or 2.1 Degree
  - Sciences, Technology, Economics or Maths
  - Sciences, Technology, Economics and Maths
  - Strong Computer Science
  - 1st Class or 2:1 in Computer Science
  - 2:1 in Maths
  - Computer Science preferred
  - or a related discipline
  - or related discipline
  - degree in Engineering
  - computer science degree
  ## requires any degree
  - Degree educated
  - Degree from a top university
  - from a top tier university
  - from a red brick university
  - 1st class or 2.1 Degree
  - recently graduated
  - 2.1 or above
  - 2.1 degree
  - good University degree
  - Russell Group University
  - 2:1 from a
  - master's degree
  - bachelor's degree
  - masters degree
  - bachelors degree
  - 2.1 Batchelors
  - computer science related degree
  - numerate degree
  - from a top 25 university
  - STEM degree
  - 2:1 degree
  - Fresh graduate
  - must be a Graduate
  - 2:1
  - Bachelor degree
  - Master degree
  - degrees in Engineering
  - degrees in Computer
  - Computer Science qualifications
  - Computer Science qualification
  - Engineering qualifications
  - Engineering qualification
  - Bachelor's
  - University Graduates
  - University Graduate
