- name: Ably
  careers_page_url: https://boards.eu.greenhouse.io/ably30/
  scraper_class: Ably

- name: Accredible
  careers_page_url: https://careers.accredible.com/?department_id=%5B12953%5D&location_id=%5B8255%5D
  scraper_class: Accredible

- name: Beam
  careers_page_url: https://careers.beam.org/jobs?department=%E2%91%82+Tech+%26+Product
  scraper_class: Beam

- name: Board Intelligence
  careers_page_url: https://apply.workable.com/board-intelligence/
  scraper_class: BoardIntelligence

- name: Bloom & Wild
  careers_page_url: https://jobs.lever.co/bloomon?location=London
  scraper_class: Lever

- name: Builder.ai
  careers_page_url: https://www.builder.ai/careers/current-openings?location=United+Kingdom&department=Engineering
  scraper_class: BuilderAi

- name: Babylon
  careers_page_url: https://www.babylonhealth.com/careers/technology
  scraper_class: Babylon

- name: Canva
  careers_page_url: https://www.lifeatcanva.com/en/jobs/?search=&team=Engineering&location=London&pagesize=20#results
  scraper_class: Canva

- name: Charlie Hr
  careers_page_url: https://apply.workable.com/charliehr/
  scraper_class: Workable

- name: Cleo
  careers_page_url: https://boards.greenhouse.io/cleoai
  scraper_class: Cleo

- name: Fresha
  careers_page_url: https://jobs.lever.co/fresha?department=Engineering
  scraper_class: Lever

- name: Funding Circle UK
  careers_page_url: https://jobs.jobvite.com/careers/funding-circle-uk/
  scraper_class: Jobvite

- name: Github
  careers_page_url: https://boards.greenhouse.io/github/
  scraper_class: Github

- name: GitLab
  careers_page_url: https://boards.greenhouse.io/gitlab/
  scraper_class: Gitlab

- name: GoCardless
  careers_page_url: https://boards.greenhouse.io/gocardless
  scraper_class: Greenhouse

# After implementing I realised they don't have a jobPosting schema
# (they have an Organization schema). I'll leave this here so I can
# check back in the future if they added it as it required a lot of
# custom javascript
#- name: Monday.com
#  careers_page_url: https://monday.com/careers
#  scraper_class: Monday

- name: Koinly
  careers_page_url: https://careers.koinly.io/jobs?location=London&query=
  scraper_class: Koinly

- name: Mindful Chef
  careers_page_url: https://mindfulchef.jobs.personio.de/
  scraper_class: MindfulChef

- name: Reedsy
  careers_page_url: https://apply.workable.com/reedsy/?lng=en#jobs
  scraper_class: Reedsy

- name: Smart Pension
  careers_page_url: https://apply.workable.com/smart-pension-1/
  scraper_class: Workable

- name: Tails.com
  careers_page_url: https://careers.tails.com/jobs
  scraper_class: Tails

- name: Zen Educate
  careers_page_url: https://jobs.lever.co/zeneducate?team=Product
  scraper_class: Lever

- name: Zeroheight
  careers_page_url: https://apply.workable.com/zeroheight/
  scraper_class: Zeroheight

