- name: Builder.ai
  careers_page_url: https://www.builder.ai/careers/current-openings?location=United+Kingdom&department=Engineering
  scraper_class: BuilderAi

- name: Babylon
  careers_page_url: https://www.babylonhealth.com/careers/technology
  scraper_class: Babylon

- name: Cleo
  careers_page_url: https://boards.greenhouse.io/cleoai
  scraper_class: Cleo

- name: Fresha
  careers_page_url: https://jobs.lever.co/fresha?department=Engineering
  scraper_class: Lever

- name: GitLab
  careers_page_url: https://boards.greenhouse.io/gitlab/
  scraper_class: Gitlab

- name: GoCardless
  careers_page_url: https://boards.greenhouse.io/gocardless
  scraper_class: Greenhouse

- name: Mindful Chef
  careers_page_url: https://mindfulchef.jobs.personio.de/
  scraper_class: MindfulChef
