- name: Builder.ai
  careers_page_url: https://www.builder.ai/careers/current-openings?location=United+Kingdom&department=Engineering
  scraper_class: BuilderAi

- name: Cleo
  careers_page_url: https://boards.greenhouse.io/cleoai
  scraper_class: Cleo

- name: GoCardless
  careers_page_url: https://boards.greenhouse.io/gocardless
  scraper_class: Greenhouse

# uses Personio ATS in case I add this for another one
- name: Mindful Chef
  careers_page_url: https://mindfulchef.jobs.personio.de/
  scraper_class: MindfulChef
