FilterRules:
  already_added_recently: already_added_recently
  black_listed: black_listed
  current_students_only: current_students_only
  title_requirements_not_met: title_requirements_not_met
  white_listed: white_listed
  wrong_job_type: wrong_job_type
JobTags:
  requires_stem_degree: requires_stem_degree
  requires_experience: requires_experience
ReviewTags:
  marked_as_approved: marked_as_approved
Groups:
  entry_level: entry_level
