Groups:
  developer: developer
Level:
  graduate: graduate
  junior: junior
  mid: mid
  senior: senior
  staff: staff
  lead: lead
  manager: manager
  principle: principle
ChatGpt:
  remote_status_from_chatgpt: remote_status_from_chatgpt
  ruby_language_from_chatgpt: programming_language_from_chatgpt
  rails_framework_from_chatgpt: rails_framework_from_chatgpt
