London:
  links:
    # "junior web developer"
    - https://companyjobsdirect.co.uk/jobs/?search_keywords=%22junior+web+developer%22&search_location=london
    # "junior software developer"
    - https://companyjobsdirect.co.uk/jobs/?search_keywords=%22junior+software+developer%22&search_location=london
    # "junior software engineer"
    - https://companyjobsdirect.co.uk/jobs/?search_keywords=%22junior+software+engineer%22&search_location=london
