London:
  links:
    # Posted last 24 hours, 100 results per page, 15 miles of London: "ruby and (developer or engineer or software)"
    - https://www.cv-library.co.uk/ruby-and-developer-or-engineer-or-software-jobs-in-london?categories=it&order=date&perpage=100&posted=1&q=ruby+and+(developer+or+engineer+or+software)&us=1
  search_by_technology: false

#London:
#  links:
#    # software AND (developer OR engineer)
#    - https://www.cv-library.co.uk/software-and-developer-or-engineer-jobs-in-london?distance=25&industry=13&order=date&perpage=100&posted=1&q=software+and+(developer+or+engineer)&us=1
#    # (backend OR back-end OR "back end") AND (developer OR Engineer)
#    - https://www.cv-library.co.uk/backend-or-back-end-or-back-end-and-developer-or-engineer-jobs-in-london?distance=25&industry=13&order=date&perpage=100&posted=1&q=(backend+or+back-end+or+%22back+end%22)+and+(developer+or+engineer)&us=1
#    # (frontend OR front-end OR "front end") AND (developer OR Engineer)
#    - https://www.cv-library.co.uk/frontend-or-front-end-or-front-end-and-developer-or-engineer-jobs-in-london?distance=25&industry=13&order=date&perpage=100&posted=1&q=(frontend+or+front-end+or+%22front+end%22)+and+(developer+or+engineer)&us=1
#    # (full-stack OR "full stack" OR fullstack) AND (engineer OR developer)
#    - https://www.cv-library.co.uk/full-stack-or-full-stack-or-fullstack-and-engineer-or-developer-jobs-in-london?distance=25&industry=13&order=date&perpage=100&posted=1&q=(full-stack+or+%22full+stack%22+or+fullstack)+and+(engineer+or+developer)&us=1
#    # ("software Development" or "software Engineering" or "web Development" or Programmer or Programming OR coding)
#    - https://www.cv-library.co.uk/software-development-or-software-engineering-or-web-development-or-programmer-or-programming-or-coding-jobs-in-london?distance=25&industry=13&order=date&perpage=100&posted=1&q=(%22software+development%22+or+%22software+engineering%22+or+%22web+development%22+or+programmer+or+programming+or+coding)&us=1
#  search_by_technology: true
#  search_by_technology_url_pattern: https://www.cv-library.co.uk/jobs-in-london?distance=25&industry=13&order=date&perpage=100&posted=1&q=(ADDTECHNOLOGIESHERE)+and+(developer+or+engineer)&us=1
