London:
# Entry level engineering
  - https://www.glassdoor.co.uk/Job/london-jobs-SRCH_IL.0,6_IC2671300.htm?jobType=entrylevel&fromAge=1&sgocId=7
# Apprentice level engineering
  - https://www.glassdoor.co.uk/Job/london-jobs-SRCH_IL.0,6_IC2671300.htm?jobType=apprenticeship&fromAge=1&sgocId=7
# Entry level IT support
  - https://www.glassdoor.co.uk/Job/london-jobs-SRCH_IL.0,6_IC2671300.htm?jobType=entrylevel&fromAge=1&sgocId=11
# Apprentice level IT support
  - https://www.glassdoor.co.uk/Job/london-jobs-SRCH_IL.0,6_IC2671300.htm?jobType=apprenticeship&fromAge=1&sgocId=11