London:
  # software AND (developer OR engineer)
  - https://uk.indeed.com/jobs?q=software+AND+%28developer+OR+engineer%29&l=London&radius=15&fromage=1&sort=date
  # (backend OR back-end OR "back end") AND (developer OR Engineer)
  - https://uk.indeed.com/jobs?q=%28frontend+OR+front-end+OR+%22front+end%22%29+AND+%28developer+OR+Engineer%29&l=london&sort=date&fromage=1
  # (frontend OR front-end OR "front end") AND (developer OR Engineer)
  - https://uk.indeed.com/jobs?q=%28frontend+OR+front-end+OR+%22front+end%22%29+AND+%28developer+OR+Engineer%29&l=london&sort=date
  # (full-stack OR "full stack" OR fullstack) AND (engineer OR developer)
  - https://uk.indeed.com/jobs?q=%28full-stack+OR+%22full+stack%22+OR+fullstack%29+AND+%28engineer+OR+developer%29&l=london&sort=date&fromage=1
  # ("software Development" or "software Engineering" or "web Development" or Programmer or Programming OR coding)
  - https://uk.indeed.com/jobs?q=%28%22software+Development%22+or+%22software+Engineering%22+or+%22web+Development%22+or+Programmer+or+Programming+OR+coding%29&l=London&radius=15&fromage=1&sort=date

  # Langauges
  # (go OR javascript OR java OR c++ OR c# OR python OR ruby OR php OR scala OR groovy OR html OR css OR elixir OR swift OR perl OR kotlin OR rust OR dart OR unity OR node OR dotnet OR sql OR SQLite) AND (developer OR engineer)
  - https://uk.indeed.com/jobs?q=%28go+OR+javascript+OR+java+OR+c%2B%2B+OR+c%23+OR+python+OR+ruby+OR+php+OR+scala+OR+groovy+OR+html+OR+css+OR+elixir+OR+swift+OR+perl+OR+kotlin+OR+rust+OR+dart+OR+unity+OR+node+OR+dotnet+OR+sql+OR+SQLite%29+AND+%28developer+OR+engineer%29&l=London&radius=15&fromage=1&sort=date

  # Frameworks
  # (.net OR vue OR vue.js OR django OR flask OR symfony OR jquery OR express OR asp OR sinatra OR drupal OR spring OR react OR angular OR AngularJS OR reactjs OR laravel OR wordpress OR rails OR salesforce OR WordPress OR Bootstrap OR splunk) AND (developer OR engineer)
  - https://uk.indeed.com/jobs?q=%28.net+OR+vue+OR+vue.js+OR+django+OR+flask+OR+symfony+OR+jquery+OR+express+OR+asp+OR+sinatra+OR+drupal+OR+spring+OR+react+OR+angular+OR+AngularJS+OR+reactjs+OR+laravel+OR+wordpress+OR+rails+OR+salesforce+OR+WordPress+OR+Bootstrap+OR+splunk%29+AND+%28developer+OR+engineer%29&l=London&radius=15&fromage=1&sort=date
