London:
  links:
    # Within 15 miles of London, posted today, "Ruby AND (developer OR engineer OR software)
    - https://www.jobserve.com/gb/en/JobListing.aspx?shid=6D016D0FE9E152169901

#London:
#  links:
#    # All London jobs posted today (not just developer jobs) - 200 results per page.
#    - https://www.jobserve.com/gb/en/JobListing.aspx?shid=6D016D0FE9E152169901
