London:
  links:
    # (ruby OR Rails) AND (engineer OR Developer) - last 24 hours
    - https://uk.linkedin.com/jobs/search?keywords=%28ruby OR Rails%29 AND %28engineer OR Developer%29&location=London%2C England%2C United Kingdom&locationId=&geoId=100495523&f_TPR=r86400&distance=10&position=1&pageNum=0
  search_by_technology: false
Remote:
  links:
    # (ruby OR Rails) AND (engineer OR Developer) - last 24 hours
    - https://uk.linkedin.com/jobs/search?keywords=%28ruby%20OR%20Rails%29%20AND%20%28engineer%20OR%20Developer%29&location=United%20Kingdom&locationId=&geoId=101165590&f_TPR=r86400&f_WT=2&position=1&pageNum=0
  search_by_technology: false
