London:
  - https://www.linkedin.com/jobs/search?keywords=Junior%2Bdeveloper&location=London%2C%2BEngland%2C%2BUnited%2BKingdom&geoId=102257491&trk=public_jobs_jobs-search-bar_search-submit&f_TP=1&currentJobId=2414828001&position=9&pageNum=0
  - https://www.linkedin.com/jobs/search?keywords=junior%20software&location=London%2C%20England%2C%20United%20Kingdom&geoId=102257491&trk=public_jobs_jobs-search-bar_search-submit&redirect=false&position=1&pageNum=0
