London:
  links:
    - https://www.reed.co.uk/jobs/jobs-in-london?keywords=software%20AND%20%28developer%20OR%20engineer%29%20AND%20ruby&datecreatedoffset=Today&proximity=15
  search_by_technology: false

#London:
#  links:
#    # software AND (developer OR engineer)
#    - https://www.reed.co.uk/jobs/jobs-in-london?keywords=software%20AND%20%28developer%20OR%20engineer%29&sortby=DisplayDate&datecreatedoffset=Today&proximity=20
#    # (backend OR back-end OR "back end") AND (developer OR Engineer)
#    - https://www.reed.co.uk/jobs/jobs-in-london?keywords=%28backend%20OR%20back-end%20OR%20%22back%20end%22%29%20AND%20%28developer%20OR%20Engineer%29&sortby=DisplayDate&datecreatedoffset=Today&proximity=20
#    # (frontend OR front-end OR "front end") AND (developer OR Engineer)
#    - https://www.reed.co.uk/jobs/jobs-in-london?keywords=%28frontend%20OR%20front-end%20OR%20%22front%20end%22%29%20AND%20%28developer%20OR%20Engineer%29&sortby=DisplayDate&datecreatedoffset=Today&proximity=20
#    # (full-stack OR "full stack" OR fullstack) AND (engineer OR developer)
#    - https://www.reed.co.uk/jobs/jobs-in-london?keywords=%28full-stack%20OR%20%22full%20stack%22%20OR%20fullstack%29%20AND%20%28engineer%20OR%20developer%29&sortby=DisplayDate&datecreatedoffset=Today&proximity=20
#    # ("software Development" or "software Engineering" or "web Development" or Programmer or Programming OR coding)
#    - https://www.reed.co.uk/jobs/jobs-in-london?keywords=%28%22software%20Development%22%20or%20%22software%20Engineering%22%20or%20%22web%20Development%22%20or%20Programmer%20or%20Programming%20OR%20coding%29&sortby=DisplayDate&datecreatedoffset=Today&proximity=20
#  search_by_technology: true
#  search_by_technology_url_pattern: https://www.reed.co.uk/jobs/jobs-in-london?keywords=%28ADDTECHNOLOGIESHERE%29%20AND%20%28developer%20OR%20engineer%29&sortby=DisplayDate&datecreatedoffset=Today&proximity=20
