London:
  links:
    # software AND (developer OR engineer)
    - https://www.totaljobs.com/jobs/software-and-developer-or-engineer/in-london?q=Software+AND+(Developer+OR+Engineer)&radius=20&postedwithin=1&Sort=2
    # (backend OR back-end OR "back end") AND (developer OR Engineer)
    - https://www.totaljobs.com/jobs/backend-or-back-end-or-back-end-and-developer-or-engineer/in-london?q=(Backend+OR+Back-End+OR+%22Back+End%22)+AND+(Developer+OR+Engineer)&radius=20&postedwithin=1&Sort=2
    # (frontend OR front-end OR "front end") AND (developer OR Engineer)
    - https://www.totaljobs.com/jobs/frontend-or-front-end-or-front-end-and-developer-or-engineer/in-london?q=(Frontend+OR+Front-End+OR+%22Front+End%22)+AND+(Developer+OR+Engineer)&radius=20&postedwithin=1&Sort=2
    # (full-stack OR "full stack" OR fullstack) AND (engineer OR developer)
    - https://www.totaljobs.com/jobs/full-stack-or-full-stack-or-fullstack-and-engineer-or-developer/in-london?q=(Full-Stack+OR+%22Full+Stack%22+OR+Fullstack)+AND+(Engineer+OR+Developer)&radius=20&postedwithin=1&Sort=2
    # ("software Development" or "software Engineering" or "web Development" or Programmer or Programming OR coding)
    - https://www.totaljobs.com/jobs/software-development-or-software-engineering-or-web-development-or-programmer-or-programming-or-coding/in-london?q=(%22Software+Development%22+Or+%22Software+Engineering%22+Or+%22Web+Development%22+Or+Programmer+Or+Programming+OR+Coding)&radius=20&postedwithin=1&Sort=2
  search_by_technology: true
  search_by_technology_url_pattern: https://www.totaljobs.com/jobs/ADDTECHNOLOGIESHERE-and-developer-or-engineer/in-london?q=(ADDTECHNOLOGIESHERE)+AND+(Developer+OR+Engineer)&radius=20&postedwithin=1&Sort=2
